; core.PL
;
; Polish translation by 50p from #sa-mp.scripting
; Huge thanks an appreciation to them
;
; (message below from 50p)
;
; Contact with me via email/hotmail: y-50p@hotmail.com
; If you know a really good C/C++ resources that could help me then don't
; hasitate to contact me because now we can write plugins with SA-MP 0.2
; and I know only basis of C/C++ (defining variables/operators/etc.)
;
; Kontakt ze mn¹ przez email/hotmail: y-50p@hotmail.com
; Jeœli znasz jakieœ bardzo dobre strony o C/C++ nie wachaj sie i daæ mi znaæ
; bo teraz mamy mo¿liwoœci pisania plugin'ow w SA-MP 0.2 a w C/C++ znam tylko
; podstawy
;

[ysi_properties]

YSI_PROP_NAME = Posiad³oœæ: "%s" Koszt: $%d Wynagrodzenie: $%d
YSI_PROP_BUY = Wpisz "/%n" aby kupiæ
YSI_PROP_OWN = Ju¿ posiadasz t¹ posesje
YSI_PROP_YOURS = Jesteœ w³aœcicielem tej posiad³oœci
YSI_PROP_OUT = "%s" zosta³o kupione przez %s (%d)
YSI_PROP_OWNER = Ta posiad³oœæ jest w³asnoœcia %s (%d)
YSI_PROP_BOUGHT = Kupileœ "%s" za $%d
YSI_PROP_NOT = Nie jesteœ w prawid³owej posiad³oœci
YSI_PROP_CP = Nie jesteœ w checkpoint'cie posiad³oœci
YSI_PROP_AFFORD = Nie mo¿esz uzyskaæ tej posiad³oœci
YSI_PROP_EARNT = Osi¹gn¹³eœ $%d z twoich posiad³oœci
YSI_PROP_SELL = Wpisz "/%n %d" aby sprzedaæ t¹ posiad³oœæ
; Mo¿esz opuœciæ parametry, ale tylko w porz¹dku od ty³u
; YSI_PROP_SELL = Wpisz "/%n %d" aby sprzedaæ t¹ posiad³oœæ za $%d

YSI_BUY_HELP_1 = Pozwala ci na kupno posiad³oœci które daj¹ zyski
YSI_BUY_HELP_2 = you money over time and can be very profitable.
YSI_BUY_HELP_3 = Musisz byæ w prawid³owej posiad³oœci aby u¿yæ tej komendy
YSI_BUY_HELP_4 = ale bêdziesz powiadomiony jeœli nie

YSI_SELL_HELP_1 = Sprzedaje posiad³oœæ któr¹ posiadasz.  To mo¿e byæ
YSI_SELL_HELP_2 = za cene mniejsz¹ ni¿ j¹ kupi³eœ.
YSI_SELL_HELP_3 = Musisz podaæ id posiad³oœci któr¹ posiadasz
YSI_SELL_HELP_4 = ale nie musisz byæ w posiad³oœci
YSI_SELL_NO_ID = Musisz podaæ prawid³owe ID posiad³oœci
YSI_SELL_CANT = Nie mo¿esz sprzedaæ tej posiad³oœci
YSI_SELL_OWNER = Nie posiadasz tej posiad³oœci
YSI_SELL_SOLD = Posiad³oœæ sprzedana za $%d

YSI_FORBIDDEN = Wchodzisz na zakazany teren
YSI_FORBIDDEN_2 = Ostrze¿enie, wchodzisz %s

YSI_LIST_MULTI = "%s": %d w³aœcicieli
YSI_LIST_FORM = "%s": w³aœciciel "%s"
YSI_LIST_PAGES = U¿yj "/%n <strona>" gdzie <strona> to 1 - %d by wylistowaæ
YSI_LIST_MORE = Znaleziono wiêcej ni¿ 8 posiad³oœci

YSI_BANK_NAME = Witaj w banku %s
YSI_BANK_WELCOME = Witaj w banku
YSI_BANK_HELP1 = Wpisz "/%n <iloœæ>" by wp³aciæ pieni¹dze
YSI_BANK_HELP2 = Wpisz "/%n <iloœæ>" by wyp³aciæ pieni¹dze
YSI_BANK_HELP3 = Wpisz "/%n" kiedykolwiek aby zobaczyæ stan konta
YSI_BANK_BALANCE = Twój aktualny stan konta to $%d
YSI_BANK_NOT = Nie jesteœ w banku
YSI_BANK_CP = Musisz byæ w checkpoint'cie banku
YSI_BANK_HELP_1 = Pozwala ci na wp³acenie pieniêdzy na konto
YSI_BANK_HELP_2 = Musisz mieæ wystarczaj¹co funduszy by wp³aciæ
YSI_BANK_HELP_3 = wymagana iloœæ i musisz byæ w banku
YSI_BANK_HELP_4 = U¿yj: "/%n <iloœæ>"
YSI_BANK_BANKED = $%d wp³acone, nowy stan konta $%d
YSI_BANK_INSUFFICIENT = Niedostateczne fundusze do transakcji

YSI_BAL_HELP = Wyœwietla twoj aktualny stan konta bankowego

YSI_WITH_HELP1 = Pozwala ci na wyp³acenie pieniêdzy z twojego konta
YSI_WITH_HELP2 = Musisz mieæ dostatecznie funduszy aby wyp³aciæ
YSI_WITH_HELP3 = wymagana iloœæ i musisz byæ w banku
YSI_WITH_HELP4 = U¿yj: "/%n <iloœæ>"
YSI_WITHDREW = $%d wyp³acone, nowy stan konta $%d

YSI_TELS_NAME = Teleportowany do %s
YSI_TELS_TELE = Teleportowany
YSI_TELS_MONEY = Nie dostatecznie funduszy, potrzebujesz $%d aby siê teleportowaæ

YSI_AMMU_NO_MONEY = Nie mo¿esz mieæ tej broni

; new
YSI_LIST_HELP_1 = Wyœwietla liste posiad³oœci i ich w³aœcicieli
YSI_LIST_HELP_2 = Jeœli jest wiêcej ni¿ 8 posiad³oœci s¹
YSI_LIST_HELP_3 = wielokrotne strony posiad³oœci
YSI_LIST_NONE = Nie znaleziono posiad³oœci

[ysi_race]

YSI_RACE_COUNTDOWN = %d
YSI_RACE_GO = GO GO GO!!!

[ysi_text]

YSI_TEXT_NOT_FOUND = Ci¹gu znaków "%s" nie znaleziono

[ysi_commands]

YSI_COMM_BLEVEL = Nie mo¿esz u¿yæ tej komendy
YSI_COMM_LIST = "/%s"
YSI_COMM_PAGES = U¿yj "/%n <strona>" gdzie <strona> to 1 - %d aby wylistowac
YSI_COMM_MORE = Znaleziono wiêcej ni¿ 8 komend

; new

YSI_COMM_HELP_1 = Wyœwietla liste komend dla skryptu
YSI_COMM_HELP_2 = Jeœli jest wiêcej ni¿ 8 komend s¹ strony
YSI_COMM_HELP_3 = Komendy s¹ pokazane z prefixami i alternatywnymi nazwami

[ysi_langs]

YSI_LANGS_HELP1 = Bez parametrów wyœwietla listê jêzyków
YSI_LANGS_HELP2 = Z parametrem ustawia twój jêzyk na jeden wybranych jêzyków
YSI_LANGS_DISP = Jêzyk %d: %s (%s)
YSI_LANGS_MORE = Wpisz "/%n" aby ponownie wyœwietliæ wiêcej jêzyków
YSI_LANGS_SET = Wpisz "/%n <id>" aby wybraæ jêzyk
YSI_LANGS_DONE = Jêzyk ustawiony na %d (%s)
YSI_LANGS_INV = Nieprawid³owy jêzyk

[ysi_help]

YSI_HELP_HELP1 = Wyœwietla pomoc o skrypcie lub komendzie.
YSI_HELP_HELP2 = Wpisz "/%n" po pomoc scryptu, "/%n <komenda>"
YSI_HELP_HELP3 = po pomoc o komendzie lub "/%n" po listê komend
YSI_HELP_NOTF = Nie znana funkcja, nie ma dostêpnej pomocy.

YSI_HELP_1 = <Tutaj nazwa twojego skryptu>
YSI_HELP_2 = przez <a tutaj twoje imie>
YSI_HELP_3 = bazowany na YSI przez Alex "Y_Less" Cole
YSI_HELP_4 = Przystosuj ten tekst w core.PL w twoim
YSI_HELP_5 = folderze scriptfiles/YSI (domyœlnie).

YSI_HELP_6 = Zostaw linie czyste jeœli nie potrzebujesz 10 linji i zostan¹ ignorowane.
YSI_HELP_7 = ; Ta linia nie bêdzie w ogole wyœwietlona w chat box'ie bo jest czysta (; oznacza komentarz)
YSI_HELP_8 =

; Ta linia jeste jedn¹ która mo¿e posiadaæ dane %n dla komend
YSI_HELP_9 = Wpisz: "/%n" po komendy i "/%n <komenda>"
YSI_HELP_10 = po pomoc o specyficznej komendzie (w³¹cznie z t¹)

[ysi_players]

YSI_LOGIN_HELP_1 = Pozwala ci siê zalogowaæ do systemu u¿ytkowników
YSI_LOGIN_HELP_2 = u¿uwaj¹c has³a z którym siê zarejestrowa³eœ.  U¿yj
YSI_LOGIN_HELP_3 = "/%n" aby sie zarejestrowaæ lub "/%n" aby do³¹czyæ do grupy

YSI_REGISTER_HELP_1 = Pozwala ci na zarejestrowanie twojego nicku na serwerze
YSI_REGISTER_HELP_2 = U¿yj "/%n <has³o>" aby siê zarejestrowaæ z has³em
YSI_REGISTER_HELP_3 = "/%n <has³o>" aby siê zalogowaæ z tym samym has³em aby
YSI_REGISTER_HELP_4 = odnowiæ twoje poprzednie zapisane statystyki i ustawienia.

YSI_GROUP_HELP_1 = Pozwala ci na dodanie twojego aktualnego nicku do innej grupy
YSI_GROUP_HELP_2 = nicków co pozwoli dwóm nickom dzielenie takich samych
YSI_GROUP_HELP_3 = statystyk.  U¿yj "/%n <nick> <has³o>" gdzie <nick> jest
YSI_GROUP_HELP_4 = istniej¹cym zarejestrowanym nickiem i <has³o> jest jego
YSI_GROUP_HELP_5 = has³em aby dodaæ ten nick.

YSI_NSGROUP_PARAMS = U¿yj: "/%n <zarejestrowany nick> <has³o nicku>"

YSI_REG_TAKEN = Przepraszam, ten nick ju¿ jest zarejestrowany.
YSI_LOGIN_WRONG = Z³e has³o.
YSI_LOGIN_INDERR = B³¹d czytania indeksu, proszê spróbowaæ ponownie.
YSI_LOGIN_LOGIN = Zalogowany!
YSI_LOGIN_NOTF = Nie znaleziono nazwy u¿ytkownika
YSI_LOGIN_NOLOAD = B³¹d przy otwieraniu pliku z danymi.
YSI_LOGIN_FAILED = Zalogowanie odmówione.
YSI_ADDU_INDER1 = Dodanie pliku u¿ytkownika b³¹d 1.
YSI_ADDU_INDER2 = Dodanie pliku u¿ytkownika b³¹d 2.
YSI_ADDU_SUCC = Rejestracja zakoñczona sukcesem.
